#!/bin/bash

# install dependencies
pip3 install -r ./requirements.txt

# import custom theme for ttkbootstrap
cp user.py $HOME/.local/lib/python3.13/site-packages/ttkbootstrap/themes/

# install build tools for Fedora
sudo dnf install -y rpmdevtools rpmlint python3-pillow-tk

# Setup build directories for RPM packages
rpmdev-setuptree