USER_THEMES = {
    "trinity-dark": {
        "type": "dark",
        "colors": {
            "primary": "#3998e7",
            "secondary": "#446488",
            "success": "#02b875",
            "info": "#17a2b8",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#ededef",
            "dark": "#282828",
            "bg": "#282828",
            "fg": "#ededef",
            "selectbg": "#446488",
            "selectfg": "#ededef",
            "border": "#3f7eb8",
            "inputfg": "#ededef",
            "inputbg": "#4a4a59",
            "active": "#4a4a59",
        },
    },
    "trinity-light": {
        "type": "light",
        "colors": {
            "primary": "#3998e7",
            "secondary": "#446488",
            "success": "#02b875",
            "info": "#17a2b8",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#ededef",
            "dark": "#4a4a59",
            "bg": "#ededef",
            "fg": "#282828",
            "selectbg": "#3998e7",
            "selectfg": "#ededef",
            "border": "#3f7eb8",
            "inputfg": "#4a4a59",
            "inputbg": "#f1f1f3",
            "active": "#e5e5e5",
        },
    },
    "heffelhoffui": {
        "type": "light",
        "colors": {
            "primary": "#115740",
            "secondary": "#c8c8c8",
            "success": "#1d966f",
            "info": "#27c995",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#eeeeee",
            "dark": "#282828",
            "bg": "#ffffff",
            "fg": "#282828",
            "selectbg": "#115740",
            "selectfg": "#ffffff",
            "border": "#1d966f",
            "inputfg": "#282828",
            "inputbg": "#eeeeee",
            "active": "#eeeeee",
        },
    },
}
